# Welcome to the Modern Data Lake.
# Feel free to modify this file to suit your needs..
---
version: '3'
x-airflow-common:
  &airflow-common
  # uncomment the image tag to use a specific image
  # comment the build & context if you want to use the built image.
  # image: 'air-prune'
  build:
    context: ./airflow-setup
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
  volumes:
    - ../dags:/opt/airflow/dags
    - ../plugins:/opt/airflow/plugins
    - ../logs:/opt/airflow/logs
    - ../spark/app:/usr/local/spark/app 
    - ../spark/resources:/usr/local/spark/resources 
  user: "${AIRFLOW_UID:-50000}:$AIRFLOW_GID:-50000}"
  env_file:
    - .env
  networks:
    - oasiscorp
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:

  # Postgre DB
  postgres:
    hostname: oasispostgres
    container_name: postgres_container
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
     - oasiscorp
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ${PWD}/postgres/create_ranger_users.sql:/docker-entrypoint-initdb.d/create_ranger_users.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    

  # Jupyter notebook
  jupyter-spark:
        hostname: myjupyter
        container_name: jupyter_container
        image: 'jupyter/pyspark-notebook:spark-3.2.0'
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ../notebooks:/home/jovyan/work/notebooks/
          - ../spark/resources/data:/home/jovyan/work/data/
          - ../spark/resources/jars:/home/jovyan/work/jars/
        restart: always
        depends_on:
                - postgres

  # Spark Master with 3 workers.
  spark-master:
    image: 'bde2020/spark-master:3.2.0-hadoop3.2'
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ../spark/app:/usr/local/spark/app
      - ../spark/resources:/usr/local/spark/resources
    ports:
       - "8181:8080"
       - "7077:7077"
    networks:
      - oasiscorp

  # Spark Worker-1
  spark-worker-1:
    image: 'bde2020/spark-worker:3.2.0-hadoop3.2'
    container_name: spark-worker-1
    depends_on: 
      - spark-master
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ../spark/app:/usr/local/spark/app 
      - ../spark/resources:/usr/local/spark/resources
    networks:
      - oasiscorp 

  # Spark Worker-2
  spark-worker-2:
    image: 'bde2020/spark-worker:3.2.0-hadoop3.2'
    container_name: spark-worker-2
    ports:
      - "8083:8081"
    depends_on: 
      - spark-master
    env_file:
      - .env
    volumes:
      - ../spark/app:/usr/local/spark/app
      - ../spark/resources:/usr/local/spark/resources
    networks:
      - oasiscorp

  # Redis DB
  redis:
    image: 'redis:latest'
    container_name: redis
    networks:
      - oasiscorp
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  # Airflow Web UI
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: webserver
    ports:
        - '8085:8080'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8085/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  # Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: scheduler
    restart: always

  # Airflow Worker 
  airflow-worker:
    <<: *airflow-common
    command: celery worker
    container_name: celery-worker
    restart: always

  # Airflow DB
  airflow-init:
    <<: *airflow-common
    command: version
    container_name: airflow-init
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}



# Volumes 
volumes:
  postgres-db-volume:
  namenode:
  datanode:


# Network Bridge Connection
networks:
  oasiscorp:
    driver: bridge